### ISSUE TITLE
Let's create a README

### ISSUE THREAD

**Issue by theo-armour** [ecumenopolis/suggestions#6]
I am very much in favor of a [release early, release often]( https://en.wikipedia.org/wiki/Release_early,_release_often ) way of doing things. So even though I don't feel the flow of ideas in the following text is as smooth, cohesive and understandable as I would like, here goes:

***

The 'suggestions' repository lacks a [README.md]( https://en.wikipedia.org/wiki/README ) file.

A readme file is an introduction to a project. Some will even say that a readme may [help a project come alive]( http://tom.preston-werner.com/2010/08/23/readme-driven-development.html ).

In any case there are typical structures for read me files to explain how to install the code and whatever. Unlike the typical GitHub project, this organization has a global, social and economic mission that goes well beyond a normal program or app. It makes sense that the readme for this repository skips some of the download and install jargon of most readme files and jumps into delineating the mission and vision, the features and benefits of this project.

It is also worth considering that this project is kind of like a startup. ( Fingers crossed that we do not need VC money and that we can bootstrap this affair. ) And that means that we cannot succeed with random, higgledy-piggledy efforts. On the contrary, because we are using our weekend and evening time, we should be highly organized with our focus and duties. We will at least need some aspects of the following:

* Elevator pitch
* Executive summary
* Gory details
	* People
	* Products
	* Marketing
	* Strategies
	* Financials

Even if this is a new endeavor we can build upon the past and [stand on the shoulders of giants]( https://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants ). We can and should follow the guidelines for creating the pitch deck of a startup or the business plan of a startup.

There is a vast array of business plan birthing tools available. Our first job is to agree which set of tools, which set of shoulders of which giants we wish stand upon.

Please do reply with links to any startup documentation strategies that you admire and why we should follow them. Let's program the program to success.

* https://piktochart.com/blog/startup-pitch-decks-what-you-can-learn/
* https://en.wikipedia.org/wiki/Business_plan
* https://www.sba.gov/course/how-write-business-plan/#course-content

**Comment by theo-armour** [comment]
A bit more

Why are readme files important?

* https://github.com/topics/readme ~ 425 entries
* https://readmetips.github.io/ ~ yours truly
* https://opensource.guide/starting-a-project/#writing-a-readme

Why are proposals so important?

When groups of people get to together to do something on an ongoing basis they usually want more certainty than just some handshakes or bowing. Therefore they establish articles of association or constitutions or club rules or whatever.

Establishing the rules of the game takes time and effort. Frequently the group falls apart and the efforts at creating rules are wasted. So very often there is some sign of an agreement prior to the actual formation. 

Examples might include:

* The American Declaration of Independence preceded the US Constitution
* Luther's 99 theses preceded the creation of the Protestant church
* Marriage proposals and engagement rings precede weddings

In a similar way the proposal to start an organization or business is an outward and visible sign of a mutual intent and agreement to begin a particular process.

Such a proposal is not about, for example, how to make a fishing pole but more how we plan to make it, market it, sell it and manage the finances. If _ecumenopolis_ is to be a success then we need to more than just build a trading floor, we must also be city planners

**Comment by schancel** [comment]
I agree READMEs are valuable and we should have one.  There is no need to persuade me, I just have not done it yet.

One thing that's important though, is that the README of this project is rather unique because:

http://ecumenopolis.net/ <-- This page is the project README

The repository README can, and should, extend this foreward.  Potential contributors need meta-information about contributing that should not necessarily be provided with the foreward/readme to ecumenopolis itself.

That meta-information is, from my perspective is:
1. How do I render the HTML.
2. How do I find the real time chat associated with this project.
3. How are things being localized.

Etc.

**Comment by theo-armour** [comment]
@schancel 

> http://ecumenopolis.net/ <-- This page is the project README

If so, then why not link to it or copy the text?

> Potential contributors need meta-information about contributing

Often that info is placed in a separate contributing file

As for the following I need more background

> How do I render the HTML.

Is your browser broke? ;-)

> How do I find the real time chat associated with this project.

Isn't a link OK? https://web.telegram.org/#/im?p=g321021001

> How are things being localized.

I often start with Google Translate

L'objectif de ce projet est de maximiser l'épanouissement humain et de minimiser les souffrances humaines. Nous croyons que nous pouvons y parvenir en cherchant à maximiser la liberté humaine. Maximiser la liberté humaine permet à la sagesse et au discernement de chacun d’être productifs dans la société pour obtenir un effet maximal. Nous savons que cela est nécessaire en raison des exemples du problème de coordination et du problème de calcul économique.

Nous croyons que nous pouvons maximiser la liberté humaine et l'épanouissement en prenant volontairement certains engagements personnels. Nous reconnaissons que nous ne savons que peu. Par conséquent, nous ne cherchons pas à créer la perfection, mais seulement à créer un accord qui fonctionne pour nous en tant qu'individus. Nous espérons que cela fonctionnera également pour tous les autres.

Nous atteindrons cet objectif en choisissant nos engagements avec soin en comprenant les dernières recherches en matière de théorie des jeux, d’intelligence en essaim, d’économie, de psychologie humaine et de connaissances de l’histoire et des succès et échecs passés.

Nous croyons que la majorité des gens devraient être capables de connaître et d’accepter volontairement ces engagements pour eux-mêmes en comprenant parfaitement leurs significations. Ce document devrait être compréhensible par la majorité des individus et être lu et compris d’ici quelques semaines. Par conséquent, nous devrions chercher à minimiser la complexité de ce document, tout en fournissant autant de références que possible pour ceux qui sont plus curieux de la raison.

En outre, si le besoin s'en fait sentir, ce document peut et doit être modifié individuellement et partagé avec d'autres. La capacité de changement est importante en raison des changements de langue au fil du temps et de la dérive sémantique. De nombreuses autres tentatives d'écriture d'une alliance comme celle-ci ont échoué à long terme en raison d'un échec d'adaptation et du développement du mysticisme autour de mots dérivant sémantiquement. Ainsi, ce document sera maintenu en unicode et dans un système de contrôle de version tel que git. De cette manière, des modifications peuvent être apportées et les modifications examinées avec un raisonnement par toute personne cherchant à mieux comprendre ce qu’elles assument.

Nous avons choisi le nom de Livre d’Ecumenopolis parce que nous cherchons à créer une citoyenneté commune. Ecumenopolis signifie "ville du monde". Afin de réaliser cette vision, nous cherchons à créer un ensemble commun de lois que chacun puisse s’engager à respecter.

Le principal mécanisme par lequel nous améliorerons la condition humaine consiste à créer un système volontaire de règles et de valeurs qui aboutissent à une action humaine claire et directe. Ces règles devraient créer un équilibre de Nash par lequel chacun s’engage volontairement à respecter ces engagements. Les engagements devraient garantir que les biens publics sont payés et produits dans des proportions raisonnables par rapport à l'activité économique totale et qu'un ensemble de lois pouvant être adoptées et suivies de deux écarts types de la population (95%).

[^ 1]: "Nous" fait désormais référence à toute personne qui s’est engagée dans ce document ou a choisi de s’identifier en tant que coauteur. C'est à vous de décider si vo
